
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcsi.h"

/*
* The configuration table for devices
*/

XCsi_Config XCsi_ConfigTable[XPAR_XCSI_NUM_INSTANCES] =
{
	{
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_DEVICE_ID,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_BASEADDR,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_CSI_LANES,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_CSI_OFFLOAD_NONIMAGE,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_CSI_EN_VC_SUPPORT,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_CSI_FIXED_VC,
		XPAR_CAPTURE_PIPELINE_MIPI_CSI2_RX_SUBSYST_0_RX_CSI_OPT3_FIXEDLANES
	}
};


