# source C:/Users/deoch/Documents/sel-embeddeddebugger/debugger/read_registers.tcl
puts [rrd r0]
puts [rrd r1]
puts [rrd r2]
puts [rrd r3]
puts [rrd r4]
puts [rrd r5]
puts [rrd r6]
puts [rrd r7]
puts [rrd r8]
puts [rrd r9]
puts [rrd r10]
puts [rrd r11]
puts [rrd r12]
puts [rrd r13]
puts [rrd r14]
puts [rrd r15]
puts [rrd r16]
puts [rrd r17]
puts [rrd r18]
puts [rrd r19]
puts [rrd r20]
puts [rrd r21]
puts [rrd r22]
puts [rrd r23]
puts [rrd r24]
puts [rrd r25]
puts [rrd r26]
puts [rrd r27]
puts [rrd r28]
puts [rrd r29]
puts [rrd r30]
puts [rrd pc]
puts [rrd sp]
puts [rrd sys 4 fpcr]
puts [rrd sys 4 fpsr]
puts [rrd sys 0 mpidr_el1]
puts [rrd sys 5 ifsr32_el2]
puts [rrd sys 5 esr_el1]
puts [rrd sys 5 esr_el2]
puts [rrd sys 5 esr_el3]
puts [rrd sys 12 isr_el1]
puts [rrd sys 1 sctlr_el3]
puts [rrd sys 2 tcr_el3]
puts [rrd sys 13 contextidr_el1]
puts [rrd sys 1 cpacr_el1]
puts [rrd sys 1 actlr_el3]
puts [rrd sys 9 pmcr_el0]
puts [rrd sys 9 pmcntenset_el0]
puts [rrd sys 9 pmovsclr_el0]
puts [rrd sys 9 pmuserenr_el0]
puts [rrd sys 9 pmintenset_el1]
puts [rrd sys 14 pmevcntr0_el0]
puts [rrd sys 14 pmevcntr1_el0]
puts [rrd sys 14 pmevcntr2_el0]
puts [rrd sys 14 pmevcntr3_el0]
puts [rrd sys 14 pmevcntr4_el0]
puts [rrd sys 14 pmevcntr5_el0]
puts [rrd sys 14 pmevtyper0_el0]
puts [rrd sys 14 pmevtyper1_el0]
puts [rrd sys 14 pmevtyper2_el0]
puts [rrd sys 14 pmevtyper3_el0]
puts [rrd sys 14 pmevtyper4_el0]
puts [rrd sys 14 pmevtyper5_el0]
puts [rrd sys 14 pmccfiltr_el0]
puts [rrd sys 1 scr_el3]
puts [rrd sys 1 cptr_el3]
puts [rrd sys 1 mdcr_el3]
puts [rrd sys 14 cntkctl_el1]
puts [rrd sys 14 cntp_tval_el0]
puts [rrd sys 14 cntp_ctl_el0]
puts [rrd sys 14 cntv_tval_el0]
puts [rrd sys 14 cntv_ctl_el0]
puts [rrd sys 14 cnthctl_el2]
puts [rrd sys 14 cnthp_tval_el2]
puts [rrd sys 14 cnthp_ctl_el2]
puts [rrd sys 14 cntps_tval_el1]
puts [rrd acpu_gic gicc_ctlr]
puts [rrd acpu_gic gicc_pmr]
puts [rrd acpu_gic gicc_bpr]
puts [rrd acpu_gic gicc_rpr]
puts [rrd acpu_gic gicc_hppir]
puts [rrd acpu_gic gicc_abpr]
puts [rrd acpu_gic gicc_ahppir]
puts [rrd acpu_gic gicc_apr0]
puts [rrd acpu_gic gicc_nsapr0]
puts [rrd acpu_gic gicd_ctlr]
puts [rrd acpu_gic gicd_ppisr]
puts [rrd acpu_gic gicd_igroupr0]
puts [rrd acpu_gic gicd_igroupr1]
puts [rrd acpu_gic gicd_igroupr2]
puts [rrd acpu_gic gicd_igroupr3]
puts [rrd acpu_gic gicd_igroupr4]
puts [rrd acpu_gic gicd_igroupr5]
puts [rrd acpu_gic gicd_isenabler0]
puts [rrd acpu_gic gicd_isenabler1]
puts [rrd acpu_gic gicd_isenabler2]
puts [rrd acpu_gic gicd_isenabler3]
puts [rrd acpu_gic gicd_isenabler4]
puts [rrd acpu_gic gicd_isenabler5]
puts [rrd acpu_gic gicd_ispendr0]
puts [rrd acpu_gic gicd_ispendr1]
puts [rrd acpu_gic gicd_ispendr2]
puts [rrd acpu_gic gicd_ispendr3]
puts [rrd acpu_gic gicd_ispendr4]
puts [rrd acpu_gic gicd_ispendr5]
puts [rrd acpu_gic gicd_isactiver0]
puts [rrd acpu_gic gicd_isactiver1]
puts [rrd acpu_gic gicd_isactiver2]
puts [rrd acpu_gic gicd_isactiver3]
puts [rrd acpu_gic gicd_isactiver4]
puts [rrd acpu_gic gicd_isactiver5]
puts [rrd acpu_gic gicd_ipriorityr0]
puts [rrd acpu_gic gicd_ipriorityr1]
puts [rrd acpu_gic gicd_ipriorityr2]
puts [rrd acpu_gic gicd_ipriorityr3]
puts [rrd acpu_gic gicd_ipriorityr4]
puts [rrd acpu_gic gicd_ipriorityr5]
puts [rrd acpu_gic gicd_ipriorityr6]
puts [rrd acpu_gic gicd_ipriorityr7]
puts [rrd acpu_gic gicd_ipriorityr8]
puts [rrd acpu_gic gicd_ipriorityr9]
puts [rrd acpu_gic gicd_ipriorityr10]
puts [rrd acpu_gic gicd_ipriorityr11]
puts [rrd acpu_gic gicd_ipriorityr12]
puts [rrd acpu_gic gicd_ipriorityr13]
puts [rrd acpu_gic gicd_ipriorityr14]
puts [rrd acpu_gic gicd_ipriorityr15]
puts [rrd acpu_gic gicd_ipriorityr16]
puts [rrd acpu_gic gicd_ipriorityr17]
puts [rrd acpu_gic gicd_ipriorityr18]
puts [rrd acpu_gic gicd_ipriorityr19]
puts [rrd acpu_gic gicd_ipriorityr20]
puts [rrd acpu_gic gicd_ipriorityr21]
puts [rrd acpu_gic gicd_ipriorityr22]
puts [rrd acpu_gic gicd_ipriorityr23]
puts [rrd acpu_gic gicd_ipriorityr24]
puts [rrd acpu_gic gicd_ipriorityr25]
puts [rrd acpu_gic gicd_ipriorityr26]
puts [rrd acpu_gic gicd_ipriorityr27]
puts [rrd acpu_gic gicd_ipriorityr28]
puts [rrd acpu_gic gicd_ipriorityr29]
puts [rrd acpu_gic gicd_ipriorityr30]
puts [rrd acpu_gic gicd_ipriorityr31]
puts [rrd acpu_gic gicd_ipriorityr32]
puts [rrd acpu_gic gicd_ipriorityr33]
puts [rrd acpu_gic gicd_ipriorityr34]
puts [rrd acpu_gic gicd_ipriorityr35]
puts [rrd acpu_gic gicd_ipriorityr36]
puts [rrd acpu_gic gicd_ipriorityr37]
puts [rrd acpu_gic gicd_ipriorityr38]
puts [rrd acpu_gic gicd_ipriorityr39]
puts [rrd acpu_gic gicd_ipriorityr40]
puts [rrd acpu_gic gicd_ipriorityr41]
puts [rrd acpu_gic gicd_ipriorityr42]
puts [rrd acpu_gic gicd_ipriorityr43]
puts [rrd acpu_gic gicd_ipriorityr44]
puts [rrd acpu_gic gicd_ipriorityr45]
puts [rrd acpu_gic gicd_ipriorityr46]
puts [rrd acpu_gic gicd_ipriorityr47]
puts [rrd acpu_gic gicd_itargetsr0]
puts [rrd acpu_gic gicd_itargetsr1]
puts [rrd acpu_gic gicd_itargetsr2]
puts [rrd acpu_gic gicd_itargetsr3]
puts [rrd acpu_gic gicd_itargetsr4]
puts [rrd acpu_gic gicd_itargetsr5]
puts [rrd acpu_gic gicd_itargetsr6]
puts [rrd acpu_gic gicd_itargetsr7]
puts [rrd acpu_gic gicd_itargetsr8]
puts [rrd acpu_gic gicd_itargetsr9]
puts [rrd acpu_gic gicd_itargetsr10]
puts [rrd acpu_gic gicd_itargetsr11]
puts [rrd acpu_gic gicd_itargetsr12]
puts [rrd acpu_gic gicd_itargetsr13]
puts [rrd acpu_gic gicd_itargetsr14]
puts [rrd acpu_gic gicd_itargetsr15]
puts [rrd acpu_gic gicd_itargetsr16]
puts [rrd acpu_gic gicd_itargetsr17]
puts [rrd acpu_gic gicd_itargetsr18]
puts [rrd acpu_gic gicd_itargetsr19]
puts [rrd acpu_gic gicd_itargetsr20]
puts [rrd acpu_gic gicd_itargetsr21]
puts [rrd acpu_gic gicd_itargetsr22]
puts [rrd acpu_gic gicd_itargetsr23]
puts [rrd acpu_gic gicd_itargetsr24]
puts [rrd acpu_gic gicd_itargetsr25]
puts [rrd acpu_gic gicd_itargetsr26]
puts [rrd acpu_gic gicd_itargetsr27]
puts [rrd acpu_gic gicd_itargetsr28]
puts [rrd acpu_gic gicd_itargetsr29]
puts [rrd acpu_gic gicd_itargetsr30]
puts [rrd acpu_gic gicd_itargetsr31]
puts [rrd acpu_gic gicd_itargetsr32]
puts [rrd acpu_gic gicd_itargetsr33]
puts [rrd acpu_gic gicd_itargetsr34]
puts [rrd acpu_gic gicd_itargetsr35]
puts [rrd acpu_gic gicd_itargetsr36]
puts [rrd acpu_gic gicd_itargetsr37]
puts [rrd acpu_gic gicd_itargetsr38]
puts [rrd acpu_gic gicd_itargetsr39]
puts [rrd acpu_gic gicd_itargetsr40]
puts [rrd acpu_gic gicd_itargetsr41]
puts [rrd acpu_gic gicd_itargetsr42]
puts [rrd acpu_gic gicd_itargetsr43]
puts [rrd acpu_gic gicd_itargetsr44]
puts [rrd acpu_gic gicd_itargetsr45]
puts [rrd acpu_gic gicd_itargetsr46]
puts [rrd acpu_gic gicd_itargetsr47]
puts [rrd acpu_gic gicd_icfgr0]
puts [rrd acpu_gic gicd_icfgr1]
puts [rrd acpu_gic gicd_icfgr2]
puts [rrd acpu_gic gicd_icfgr3]
puts [rrd acpu_gic gicd_icfgr4]
puts [rrd acpu_gic gicd_icfgr5]
puts [rrd acpu_gic gicd_icfgr6]
puts [rrd acpu_gic gicd_icfgr7]
puts [rrd acpu_gic gicd_icfgr8]
puts [rrd acpu_gic gicd_icfgr9]
puts [rrd acpu_gic gicd_icfgr10]
puts [rrd acpu_gic gicd_icfgr11]
puts [rrd acpu_gic gicd_spisr0]
puts [rrd acpu_gic gicd_spisr1]
puts [rrd acpu_gic gicd_spisr2]
puts [rrd acpu_gic gicd_spisr3]
puts [rrd acpu_gic gicd_spisr4]
puts [rrd acpu_gic gicd_spendsgir0]
puts [rrd acpu_gic gicd_spendsgir1]
puts [rrd acpu_gic gicd_spendsgir2]
puts [rrd acpu_gic gicd_spendsgir3]
puts [rrd sys 6 far_el3]
puts [rrd sys 12 vbar_el3]
puts [rrd sys 2 ttbr0_el3]
puts [rrd sys 10 mair_el3]
puts [rrd sys 10 amair_el3]
puts [rrd sys 7 par_el1]
puts [rrd sys 13 tpidr_el0]
puts [rrd sys 13 tpidrro_el0]
puts [rrd sys 13 tpidr_el1]
puts [rrd sys 13 tpidr_el3]
puts [rrd sys 12 rmr_el3]
puts [rrd sys 1 sder32_el3]
puts [rrd sys 14 cntfrq_el0]
puts [rrd sys 14 cntp_cval_el0]
puts [rrd sys 14 cntv_cval_el0]
puts [rrd sys 14 cntvoff_el2]
puts [rrd sys 14 cnthp_cval_el2]
puts [rrd sys 14 cntps_cval_el1]
puts [rrd sys 14 cntps_ctl_el1]
puts [rrd sys 4 elr_el1]
puts [rrd sys 4 elr_el2]
puts [rrd sys 4 elr_el3]
puts [rrd vfp v0]
puts [rrd vfp v1]
puts [rrd vfp v2]
puts [rrd vfp v3]
puts [rrd vfp v4]
puts [rrd vfp v5]
puts [rrd vfp v6]
puts [rrd vfp v7]
puts [rrd vfp v8]
puts [rrd vfp v9]
puts [rrd vfp v10]
puts [rrd vfp v11]
puts [rrd vfp v12]
puts [rrd vfp v13]
puts [rrd vfp v14]
puts [rrd vfp v15]
puts [rrd vfp v16]
puts [rrd vfp v17]
puts [rrd vfp v18]
puts [rrd vfp v19]
puts [rrd vfp v20]
puts [rrd vfp v21]
puts [rrd vfp v22]
puts [rrd vfp v23]
puts [rrd vfp v24]
puts [rrd vfp v25]
puts [rrd vfp v26]
puts [rrd vfp v27]
puts [rrd vfp v28]
puts [rrd vfp v29]
puts [rrd vfp v30]
puts [rrd vfp v31]
