
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xi2srx.h"

/*
* The configuration table for devices
*/

XI2srx_Config XI2srx_ConfigTable[XPAR_XI2SRX_NUM_INSTANCES] =
{
	{
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_DEVICE_ID,
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_BASEADDR,
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_DWIDTH,
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_IS_MASTER,
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_NUM_CHANNELS,
		XPAR_AUDIO_SS_0_I2S_RECEIVER_0_32BIT_LR
	}
};


